### ISSUE TITLE
error when test the generated database 1000 queries sam single

### ISSUE THREAD

**Issue by DuongNH92** [Jamesyang2333/SAM#5]
I got below error when try to run 1000 test queries on the generated database sam single. It only occur with "dmv" database, the "census" run is ok.

python query_execute_single.py --dataset dmv --data-file ./generated_data_tables/dmv.csv --query-file ./queries/dmv_test.txt

Traceback (most recent call last):
  File "query_execute_single.py", line 43, in <module>
    cols = [sample_table.columns[sample_table.ColumnIndex(col)] for col in train_data_raw['column'][i]]
  File "query_execute_single.py", line 43, in <listcomp>
    cols = [sample_table.columns[sample_table.ColumnIndex(col)] for col in train_data_raw['column'][i]]
  File "/home/mltest/SAM/sam_single/common.py", line 152, in ColumnIndex
    assert name in self.name_to_index
AssertionError

**Comment by DuongNH92** [comment]
Otherwhile, When I run SAM model training from the full MSCN dataset, it require a file name "dmvworkload_with_card_100000.txt". So, where I can get this file? Thanks!

  File "train_uae.py", line 545, in TrainTask
    with open(file_str, 'r', encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../queries/dmvworkload_with_card_100000.txt'

**Comment by Jamesyang2333** [comment]
Hi Duong, thanks for raising the two issues, I have pushed the fix for both. The first issue was because the generated data file having the wrong header. For the second issue, the training queries are under ./sam_single/queries, i.e., dmv_train.txt and census_train.txt. The wrong file names were put in the training script. I notice you want to train SAM from MSCN dataset, as MSCN queries are for IMDB, you should be using the multiple relation version of SAM.

**Comment by DuongNH92** [comment]
Thanks for your support. I will check all issues.
